homepage: "https://goessner.net/articles/JsonPath/"
language: jvm
main_repo: "https://github.com/json-path/JsonPath.git"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
primary_contact: "pwebb@vmware.com"
auto_ccs:
  - "wilkinsona@vmware.com"
vendor_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "schaich@code-intelligence.com"
  - "bug-disclosure@code-intelligence.com"